### ISSUE TITLE
Different size nodes ---> skewed edge symbols

### ISSUE THREAD

**Issue by angelbeltran** [russross/theory#1]
I built two nodes, one a "big node" and the second a "huge node" with an edge directed from the first to the second with a symbols of "btex \Sigma \cup {\epsilon} etex", and the symbols were not placed evenly spaced along the edge between the nodes. They were closer to the smaller node. Cheers.

**Comment by russross** [comment]
The macros assume a single size for an entire figure. You may be better off
sticking to a single size.
- Russ
